apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "03627687"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/log
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
