apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "03627687"
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/log
      - nodes/proxy
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "03627687"
  namespace: "monitoring-external-services"
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - namespaces
    verbs:
      - get
      - list
      - watch
